'use strict';
// Native opening/clipboard calls are intercepted. File mutations use an isolated
// real Suite server and newly-created synthetic roots, never a personal workspace.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),net=require('node:net');
const {spawn}=require('node:child_process');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function playwright(){for(const name of [process.env.SUITE_PLAYWRIGHT_MODULE,'playwright','playwright-core'].filter(Boolean)){try{return require(name);}catch{}}const links=path.join(process.env.LOCALAPPDATA||'','ms-playwright','.links');if(fs.existsSync(links))for(const file of fs.readdirSync(links)){try{return require(fs.readFileSync(path.join(links,file),'utf8').trim());}catch{}}throw new Error('Playwright is required.');}
async function freePort(){const server=net.createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;await new Promise(resolve=>server.close(resolve));return port;}
async function waitFor(page,predicate,value){const deadline=Date.now()+20000;while(Date.now()<deadline){if(await page.evaluate(predicate,value))return;await delay(60);}throw new Error('Browser condition timed out: '+predicate.toString());}
async function stopChild(child){if(!child||child.exitCode!==null)return;child.kill('SIGTERM');await Promise.race([new Promise(resolve=>child.once('exit',resolve)),delay(4000)]);if(child.exitCode===null)child.kill('SIGKILL');}
async function main(){
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'suite-file-keys-')),fixture=path.join(temp,'files'),other=path.join(temp,'other'),artifacts=process.env.SUITE_BROWSER_ARTIFACT_DIR||path.join(temp,'artifacts');
 fs.mkdirSync(fixture);fs.mkdirSync(other);fs.mkdirSync(artifacts,{recursive:true});fs.mkdirSync(path.join(fixture,'Dest'));fs.mkdirSync(path.join(fixture,'Nested'));
 for(const name of ['alpha.txt','beta.txt','gamma.txt','中文材料.txt'])fs.writeFileSync(path.join(fixture,name),'SYNTHETIC_'+name,'utf8');fs.writeFileSync(path.join(fixture,'Nested','deep.txt'),'DEEP_CONTENT_KEYWORD 中文全文内容','utf8');
 const port=await freePort(),url=`http://127.0.0.1:${port}`,output=fs.openSync(path.join(temp,'server.log'),'a');
 const server=spawn(process.env.SUITE_PYTHON||'python',['-m','suite.server','--port',String(port),'--data-dir',path.join(temp,'data'),'--isolated','--empty-roots'],{cwd:root,env:{...process.env,PYTHONUNBUFFERED:'1'},stdio:['ignore',output,output],windowsHide:true});server.on('error',()=>{});
 let browser=null,page=null,boot;const checks=[];const mark=name=>{checks.push(name);console.log('PASS '+name);};
 try{
  const deadline=Date.now()+35000;while(Date.now()<deadline){try{const response=await fetch(url+'/api/health',{signal:AbortSignal.timeout(1500)});if(response.ok){const bootstrap=await fetch(url+'/api/suite/bootstrap',{signal:AbortSignal.timeout(15000)});if(bootstrap.ok){boot=await bootstrap.json();break;}}}catch{}if(server.exitCode!==null)throw new Error('Test server exited');await delay(150);}assert(boot,'Isolated server ready');
  const write=async(endpoint,body)=>{const response=await fetch(url+endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':boot.csrf,Origin:url},body:JSON.stringify(body)});assert(response.ok,`${endpoint}: ${await response.clone().text()}`);return response.json();};
  const rootInfo=await write('/api/suite/roots',{path:fixture,label:'Synthetic files'}),otherInfo=await write('/api/suite/roots',{path:other,label:'Synthetic other'});const rootId=rootInfo.id||rootInfo.root?.id,otherId=otherInfo.id||otherInfo.root?.id;assert(rootId&&otherId);
  browser=await playwright().chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(20000);const errors=[],nativeCalls=[],mutations=[],searchCalls=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/api/suite/files/clipboard',async route=>{const body=route.request().postDataJSON();nativeCalls.push({kind:'clipboard',body});await route.fulfill({json:{system_clipboard:true,count:body.paths.length,mode:body.mode}});});
  await page.route('**/api/suite/files/open',async route=>{nativeCalls.push({kind:'open',body:route.request().postDataJSON()});await route.fulfill({json:{opened:true}});});
  page.on('request',request=>{if(request.url().includes('/api/suite/files/operation'))mutations.push(request.postDataJSON());if(request.url().includes('/api/suite/files/search?'))searchCalls.push(request.url());});
  await page.route('**/api/suite/native-tools',route=>route.fulfill({json:{tools:[{id:'files',can_launch:true,accepts_root:false,scope:'independent_local_gui'},{id:'processes',can_launch:false,reason:'合成环境：缺少图形运行环境'}]}}));
  await page.route('**/api/suite/native-tools/files/launch',route=>{const request=route.request();assert.deepEqual(request.postDataJSON(),{});assert.equal(request.headers()['x-csrf-token'],boot.csrf);nativeCalls.push({kind:'launch',body:request.postDataJSON()});return route.fulfill({json:{launched:true,detail:'合成完整窗口已启动'}});});
  const row=name=>page.locator(`.file-row[aria-label="${name}"]`),selected=()=>page.locator('.file-row[aria-selected="true"]'),idle=()=>waitFor(page,()=>document.querySelector('#file-selection-status')&&!document.querySelector('#file-selection-status')?.textContent.includes('操作中'));
  await page.goto(url+'/#files');await page.locator('#file-root').selectOption(rootId);await row('alpha.txt').waitFor();await idle();
  await page.locator('[data-action="native-tool-launch"][data-tool-id="files"]').click();await waitFor(page,()=>document.querySelector('#toast')?.textContent.includes('合成完整窗口'));assert.equal(nativeCalls.at(-1).kind,'launch');assert.equal(await page.locator('#file-path').inputValue(),'');mark('Complete original workbench dispatches only the fixed authenticated launch action');
  await row('Dest').click();assert.equal(await page.locator('#file-path').inputValue(),'');assert.equal(await selected().count(),1);mark('Single-click folder selects without navigating');
  await page.locator('#file-table').focus();await page.keyboard.press('End');assert.equal(await selected().first().getAttribute('aria-label'),'中文材料.txt');await page.keyboard.press('Home');assert.equal(await selected().first().getAttribute('aria-label'),'Dest');await page.keyboard.press('ArrowDown');assert.equal(await selected().first().getAttribute('aria-label'),'Nested');await page.keyboard.press('ArrowDown');await waitFor(page,()=>document.querySelector('#file-preview')?.textContent.includes('SYNTHETIC_alpha.txt'));assert.equal(await selected().first().getAttribute('aria-label'),'alpha.txt');mark('Home/End and arrows move selection with real previews');
  await page.keyboard.press('Shift+ArrowDown');assert.equal(await selected().count(),2);await row('gamma.txt').click({modifiers:['Control']});assert.equal(await selected().count(),3);await page.keyboard.press('Control+a');assert.equal(await selected().count(),6);await page.keyboard.press('Escape');assert.equal(await selected().count(),0);mark('Shift ranges, Ctrl click, Select all and Escape work');
  await row('alpha.txt').click();await row('beta.txt').click({modifiers:['Control']});await page.keyboard.press('Control+c');await waitFor(page,()=>document.querySelector('#toast')?.textContent.includes('资源管理器'));assert.deepEqual(nativeCalls.at(-1).body,{root_id:rootId,paths:['alpha.txt','beta.txt'],mode:'copy'});
  await row('Dest').dblclick();await waitFor(page,()=>document.querySelector('#file-path')?.value==='Dest');await page.keyboard.press('Control+v');await waitFor(page,()=>document.querySelector('#file-rows')?.textContent.includes('beta.txt'));await idle();assert(fs.existsSync(path.join(fixture,'Dest','alpha.txt')));assert(fs.existsSync(path.join(fixture,'beta.txt')));mark('Ctrl C/V copies multiple real files into a folder');
  await page.keyboard.press('Control+v');await row('alpha - 副本.txt').waitFor();await idle();assert.equal(fs.readFileSync(path.join(fixture,'Dest','alpha - 副本.txt'),'utf8'),'SYNTHETIC_alpha.txt');mark('Repeated paste creates copies and never overwrites originals');
  await page.keyboard.press('Alt+ArrowLeft');await row('gamma.txt').waitFor();await idle();assert.equal(await page.locator('#file-path').inputValue(),'');await page.keyboard.press('Alt+ArrowRight');await row('alpha - 副本.txt').waitFor();await idle();assert.equal(await page.locator('#file-path').inputValue(),'Dest');await page.keyboard.press('Alt+ArrowUp');await row('gamma.txt').waitFor();await idle();mark('Alt back/forward/up preserve folder history');
  await row('gamma.txt').click();await page.keyboard.press('Control+x');await waitFor(page,()=>document.querySelector('#file-selection-status')?.textContent.includes('待移动'));await idle();await page.locator('#file-root').selectOption(otherId);await page.locator('#file-table').focus();await page.keyboard.press('Control+v');await row('gamma.txt').waitFor();await idle();assert(!fs.existsSync(path.join(fixture,'gamma.txt')));assert(fs.existsSync(path.join(other,'gamma.txt')));mark('Ctrl X/V moves files across registered roots');
  await row('gamma.txt').click();await page.keyboard.press('F2');await page.locator('#dialog-path').fill('中文重命名.txt');await page.locator('#dialog-path').press('Enter');await row('中文重命名.txt').waitFor();await idle();assert(!fs.existsSync(path.join(other,'gamma.txt')));assert(fs.existsSync(path.join(other,'中文重命名.txt')));mark('F2 renames using normal Chinese text input');
  await row('中文重命名.txt').click();await page.keyboard.press('F2');await page.locator('#dialog-path').fill('');await page.locator('#action-dialog [value="cancel"]').last().click();assert.equal(await page.locator('#action-dialog').isVisible(),false);assert(fs.existsSync(path.join(other,'中文重命名.txt')));mark('Cancel an empty required name without changing files');
  await row('中文重命名.txt').click();await page.keyboard.press('Delete');await page.locator('#action-dialog').waitFor({state:'visible'});assert(fs.existsSync(path.join(other,'中文重命名.txt')),'Delete waits for confirmation');await page.locator('#dialog-confirm').click();await waitFor(page,()=>!document.querySelector('#file-rows')?.textContent.includes('中文重命名.txt'));await idle();assert(!fs.existsSync(path.join(other,'中文重命名.txt')));await page.locator('#file-table').focus();await page.keyboard.press('Control+z');await row('中文重命名.txt').waitFor();await idle();assert.equal(fs.readFileSync(path.join(other,'中文重命名.txt'),'utf8'),'SYNTHETIC_gamma.txt');mark('Delete requires confirmation and Ctrl Z restores exact bytes');
  await row('中文重命名.txt').click();await page.keyboard.press('Enter');await waitFor(page,()=>document.querySelector('#toast')?.textContent.includes('原应用'));assert.deepEqual(nativeCalls.at(-1).body,{root_id:otherId,path:'中文重命名.txt'});mark('Enter dispatches the scoped native-open API, not a download');
  const beforeInput=mutations.length,clipBefore=nativeCalls.filter(call=>call.kind==='clipboard').length;await page.locator('#file-search').focus();await page.keyboard.press('Control+a');await page.keyboard.press('Control+x');await page.keyboard.press('Delete');await page.keyboard.press('F2');assert.equal(await page.locator('#action-dialog').isVisible(),false);assert.equal(mutations.length,beforeInput);assert.equal(nativeCalls.filter(call=>call.kind==='clipboard').length,clipBefore);mark('Text input copy/cut/Delete/F2 never changes selected files');
  await page.locator('#file-root').selectOption(rootId);await row('alpha.txt').waitFor();await idle();await page.locator('#file-table').focus();await page.keyboard.press('Control+f');assert.equal(await page.locator('#file-search').evaluate(el=>el===document.activeElement),true);await page.locator('#file-search').fill('alpha');await waitFor(page,()=>document.querySelectorAll('.file-row').length===1);await page.locator('#file-search').fill('DEEP_CONTENT_KEYWORD');await page.locator('#file-search').press('Enter');await row('deep.txt').waitFor();await idle();assert((await row('deep.txt').innerText()).includes('Nested/deep.txt'));assert(searchCalls.length);mark('Search live-filters names; Enter finds actual nested document content');
  const searchBefore=searchCalls.length;await page.locator('#file-search').evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',keyCode:229,isComposing:true,bubbles:true,cancelable:true}));el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));});await delay(200);assert.equal(searchCalls.length,searchBefore);mark('IME Enter/key229 does not start a recursive search');
  await page.locator('#file-search').fill('');await row('alpha.txt').waitFor();await idle();await row('alpha.txt').click();const beforeIME=mutations.length,openBefore=nativeCalls.length;await row('alpha.txt').evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));for(const key of ['Enter','Delete','F2','c'])el.dispatchEvent(new KeyboardEvent('keydown',{key,ctrlKey:key==='c',keyCode:229,isComposing:true,bubbles:true,cancelable:true}));el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));});await delay(200);assert.equal(mutations.length,beforeIME);assert.equal(nativeCalls.length,openBefore);assert.equal(await page.locator('#action-dialog').isVisible(),false);mark('Chinese composition never opens, deletes, renames or copies a file');
  await page.locator('#file-table').focus();await page.keyboard.press('Control+l');await page.locator('#file-path').fill('Nested');await page.locator('#file-path').press('Enter');await row('deep.txt').waitFor();await idle();await page.locator('#file-table').focus();await page.keyboard.press('Backspace');await row('alpha.txt').waitFor();await idle();mark('Ctrl L and Backspace navigate within the registered root');
  await row('alpha.txt').click();await row('beta.txt').click({modifiers:['Control']});await page.keyboard.press('Delete');await page.locator('#dialog-confirm').click();await waitFor(page,()=>!document.querySelector('#file-rows')?.textContent.includes('alpha.txt'));await idle();await page.locator('#file-table').focus();await page.keyboard.press('Control+z');await row('alpha.txt').waitFor();await idle();await row('beta.txt').waitFor();await idle();mark('Batch recycle and undo recover all selected files');
  await row('alpha.txt').click();await page.keyboard.press('F5');await row('alpha.txt').waitFor();await idle();assert.equal(await row('alpha.txt').getAttribute('aria-selected'),'true');await page.locator('[data-action="file-shortcuts"]').click();await page.locator('#action-dialog').waitFor({state:'visible'});assert((await page.locator('#dialog-body').innerText()).includes('Ctrl + C / X / V'));await page.locator('#dialog-confirm').click();mark('Refresh retains selection and keyboard help describes actual operations');
  await page.screenshot({path:path.join(artifacts,'suite-file-keys-desktop.png'),fullPage:true});await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(artifacts,'suite-file-keys-mobile.png'),fullPage:true});mark('File keyboard interface fits 375px');assert.deepEqual(errors,[]);mark('No browser exceptions');
  console.log(JSON.stringify({result:'passed',checks:checks.length,artifacts,temp},null,2));
 }catch(error){if(page)try{await page.screenshot({path:path.join(artifacts,'suite-file-keys-failure.png'),fullPage:true});console.error('DIAGNOSTIC '+JSON.stringify(await page.evaluate(()=>({path:document.querySelector('#file-path')?.value,selection:document.querySelector('#file-selection-status')?.textContent,toast:document.querySelector('#toast')?.textContent,body:document.querySelector('#dialog-body')?.textContent}))));}catch{}throw error;}
 finally{if(browser)await browser.close();try{if(boot)await fetch(url+'/api/suite/shutdown',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':boot.csrf,Origin:url},body:'{}',signal:AbortSignal.timeout(5000)});}catch{}await stopChild(server);fs.closeSync(output);}
}
main().catch(error=>{console.error(error.stack||error.message);process.exitCode=1;});
