'use strict';
// A test-only TLS loopback proxy fronts an isolated real Suite. No live tunnel, account,
// native clipboard/open/GUI, recorder, device, or model is used.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),net=require('node:net'),http=require('node:http'),https=require('node:https'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const password='synthetic-only-suite-password';
function playwright(){for(const name of [process.env.SUITE_PLAYWRIGHT_MODULE,'playwright','playwright-core'].filter(Boolean)){try{return require(name);}catch{}}const links=path.join(process.env.LOCALAPPDATA||'','ms-playwright','.links');if(fs.existsSync(links))for(const file of fs.readdirSync(links)){try{return require(fs.readFileSync(path.join(links,file),'utf8').trim());}catch{}}throw new Error('Playwright is required.');}
async function freePort(){const server=net.createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;await new Promise(resolve=>server.close(resolve));return port;}
async function waitFor(page,predicate,value){const deadline=Date.now()+20000;while(Date.now()<deadline){if(await page.evaluate(predicate,value))return;await delay(60);}throw new Error('Browser condition timed out: '+predicate.toString());}
async function runPython(python,args,cwd){const child=spawn(python,args,{cwd,stdio:['ignore','pipe','pipe'],windowsHide:true});let error='';child.stderr.on('data',chunk=>error+=chunk);await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>code===0?resolve():reject(new Error('Synthetic Python preparation failed: '+error)));});}
function ephemeralTls(){
 // Minimal self-signed X.509 certificate from Node built-ins; private material
 // exists only in this test process and is never written or committed.
 const der=(tag,...items)=>{const body=Buffer.concat(items),size=body.length,bytes=[];let n=size;while(n){bytes.unshift(n&255);n=Math.floor(n/256);}return Buffer.concat([Buffer.from([tag,...(size<128?[size]:[128|bytes.length,...bytes])]),body]);};
 const seq=(...items)=>der(0x30,...items),oid=hex=>der(6,Buffer.from(hex,'hex')),integer=value=>der(2,Buffer.from(value));
 const algorithm=seq(oid('2a864886f70d01010b'),der(5));
 const name=seq(der(0x31,seq(oid('550403'),der(12,Buffer.from('Synthetic Suite TLS')))));
 const keys=crypto.generateKeyPairSync('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'der'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});
 const serial=crypto.randomBytes(16);serial[0]=(serial[0]&0x7f)||1;
 const tbs=seq(der(0xa0,integer([2])),integer(serial),algorithm,name,seq(der(24,Buffer.from('20200101000000Z')),der(24,Buffer.from('20900101000000Z'))),name,keys.publicKey);
 const cert=seq(tbs,algorithm,der(3,Buffer.from([0]),crypto.sign('RSA-SHA256',tbs,keys.privateKey)));
 return {key:keys.privateKey,cert:'-----BEGIN CERTIFICATE-----\n'+cert.toString('base64').match(/.{1,64}/g).join('\n')+'\n-----END CERTIFICATE-----\n'};
}
async function main(){
 const repo=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'suite-remote-browser-')),data=path.join(temp,'data'),folder=path.join(temp,'selected'),artifacts=process.env.SUITE_BROWSER_ARTIFACT_DIR||path.join(temp,'artifacts'),config=path.join(temp,'remote.json'),python=process.env.SUITE_PYTHON||'python';
 fs.mkdirSync(folder);fs.mkdirSync(artifacts,{recursive:true});fs.mkdirSync(path.join(folder,'Dest'));fs.writeFileSync(path.join(folder,'来源材料.txt'),'SYNTHETIC_REMOTE_DOWNLOAD 中文材料','utf8');
 const requests=[],nativeRequests=[],port=await freePort(),local=`http://127.0.0.1:${port}`;
 const proxy=https.createServer(ephemeralTls(),(request,response)=>{
  const url=new URL(request.url,'https://127.0.0.1');requests.push({method:request.method,path:url.pathname});if(['/api/suite/files/open','/api/suite/files/clipboard'].includes(url.pathname)||url.pathname.includes('/launch'))nativeRequests.push(url.pathname);
  const upstream=http.request(local+request.url,{method:request.method,headers:{...request.headers,'cf-connecting-ip':'198.51.100.21'}},source=>{response.writeHead(source.statusCode,source.headers);source.pipe(response);});
  upstream.setTimeout(30000,()=>upstream.destroy(new Error('Synthetic HTTPS proxy timeout')));upstream.on('error',()=>{if(!response.headersSent)response.writeHead(502);response.end();});request.pipe(upstream);
 });await new Promise(resolve=>proxy.listen(0,'127.0.0.1',resolve));const origin=`https://127.0.0.1:${proxy.address().port}`;
 const account=path.join(data,'workos','authentication');fs.writeFileSync(config,JSON.stringify({origin,authentication_dir:account}));
 await runPython(python,['-B','-c','import sys; from suite.remote_access import _passwords; _passwords.PasswordAuth(sys.argv[1]).configure_password(sys.argv[2])',account,password],repo);
 const log=fs.openSync(path.join(temp,'server.log'),'a');
 const server=spawn(python,['-B','-c','from tests.test_remote_access import SERVER_FIXTURE; exec(SERVER_FIXTURE)','--port',String(port),'--data-dir',data,'--isolated','--empty-roots','--remote-config',config],{cwd:repo,stdio:['ignore',log,log],env:{...process.env,PYTHONUNBUFFERED:'1'},windowsHide:true});server.on('error',()=>{});
 let browser,page,localBoot;const checks=[];const mark=name=>{checks.push(name);console.log('PASS '+name);};
 try{
  const deadline=Date.now()+35000;while(Date.now()<deadline){try{const response=await fetch(local+'/api/suite/bootstrap',{signal:AbortSignal.timeout(1500)});if(response.ok){localBoot=await response.json();break;}}catch{}if(server.exitCode!==null)throw new Error('Synthetic remote server exited');await delay(150);}assert(localBoot,'Isolated Suite ready');
  const registered=await fetch(local+'/api/suite/roots',{method:'POST',headers:{Origin:local,'Content-Type':'application/json','X-CSRF-Token':localBoot.csrf},body:JSON.stringify({path:folder,label:'Synthetic remote files'})});assert(registered.ok);const root=await registered.json();
  browser=await playwright().chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,ignoreHTTPSErrors:true,serviceWorkers:'block'});page=await context.newPage();page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await context.route(url=>url.origin!==origin,route=>route.abort());
  const remoteRead=endpoint=>page.evaluate(async endpoint=>{const response=await fetch(endpoint,{credentials:'same-origin'});return{status:response.status,data:await response.json()};},endpoint);
  const anonymous=await context.request.get(origin+'/',{maxRedirects:0});assert.equal(anonymous.status(),303);assert.equal(anonymous.headers().location,'/auth/login');
  await page.goto(origin+'/#workos');await page.locator('main[data-mode="login"]').waitFor();assert(new URL(page.url()).pathname==='/auth/login');mark('Anonymous gateway redirects to the shared safe HTTPS login page');
  await page.locator('input[name="username"]').fill('workos-user');await page.locator('input[name="password"]').fill(password);await page.locator('form button').click();await page.locator('#workos-frame').waitFor();await page.frameLocator('#workos-frame').locator('#main[aria-busy="false"]').waitFor();mark('HTTPS cookie login opens Suite and its same-origin WorkOS iframe');
  const frame=page.frameLocator('#workos-frame');await frame.locator('[data-action="start-create-project"]').click();await frame.locator('#field-name').fill('Synthetic remote browser project');await frame.locator('#modal-submit').click();await frame.locator('#modal').waitFor({state:'hidden'});
  const state=(await remoteRead('/api/state')).data,project=state.projects.find(item=>item.name==='Synthetic remote browser project');assert(project);await page.goto(origin+'/#ideas');await page.locator('#idea-text').waitFor();await page.locator('#idea-project').selectOption(project.id);await page.locator('#idea-text').fill('Synthetic remote linked idea');await page.locator('#idea-save').click();await waitFor(page,()=>document.querySelector('#idea-list')?.textContent.includes('Synthetic remote linked idea'));assert((await remoteRead('/api/state')).data.notes.some(note=>note.project_id===project.id&&note.body==='Synthetic remote linked idea'));mark('Project creation in the iframe and Suite idea sharing use the same persisted records');
  await page.goto(origin+'/#files');await page.locator('#file-root').selectOption(root.id);await waitFor(page,id=>document.querySelector('#file-root')?.value===id&&document.querySelector('#file-workbench')?.getAttribute('aria-busy')==='false',root.id);const row=name=>page.locator(`.file-row[aria-label="${name}"]`);await row('来源材料.txt').click();await waitFor(page,()=>document.querySelector('#file-preview')?.textContent.includes('SYNTHETIC_REMOTE_DOWNLOAD'));assert.equal(await page.locator('[data-action="root-add"]').isDisabled(),true);assert.equal(await page.locator('[data-action="native-tool-launch"]').count(),0);mark('Remote file preview remains scoped and host-only directory/GUI controls are unavailable');
  await page.locator('#file-table').focus();await page.keyboard.press('Control+c');await waitFor(page,()=>document.querySelector('#file-selection-status')?.textContent.includes('已复制'));await row('Dest').dblclick();await waitFor(page,()=>document.querySelector('#file-path')?.value==='Dest'&&document.querySelector('#file-workbench')?.getAttribute('aria-busy')==='false');await page.keyboard.press('Control+v');await row('来源材料.txt').waitFor();await waitFor(page,()=>document.querySelector('#file-workbench')?.getAttribute('aria-busy')==='false');assert.equal(fs.readFileSync(path.join(folder,'Dest','来源材料.txt'),'utf8'),'SYNTHETIC_REMOTE_DOWNLOAD 中文材料');assert.equal(nativeRequests.length,0);mark('Remote Ctrl C/V copies actual registered files using no host clipboard or native open');
  await page.locator('#file-table').focus();const [download]=await Promise.all([page.waitForEvent('download'),page.keyboard.press('Enter')]);const downloaded=path.join(temp,'download.txt');await download.saveAs(downloaded);assert.equal(fs.readFileSync(downloaded,'utf8'),'SYNTHETIC_REMOTE_DOWNLOAD 中文材料');assert.equal(nativeRequests.length,0);mark('Remote Enter downloads exact original bytes to the browser rather than the host desktop');
  await page.goto(origin+'/#qwen');await page.locator('#qwen-live-status').waitFor();
  for(const selector of ['[data-action="qwen-start"]','[data-action="qwen-stop"]','[data-action="qwen-trigger"]','#qwen-hotkey'])assert.equal(await page.locator(selector).isDisabled(),true);assert.equal(await page.locator('#qwen-original-panel').count(),0);mark('Remote Qwen is read-only and cannot pause, trigger, change settings, or link to client localhost');
  await page.goto(origin+'/#phone');await waitFor(page,()=>document.querySelector('#content')?.textContent.includes('本机'));assert.equal(await page.locator('[data-action="phone-mirror"]').count(),0);await page.goto(origin+'/#processes');await waitFor(page,()=>document.querySelector('#content')?.textContent.includes('本机'));assert.equal(requests.some(request=>request.path==='/api/suite/phone/devices'||request.path==='/api/suite/processes'),false);mark('Remote device/process views explain host-only scope without querying or controlling them');
  const forbidden=await page.evaluate(async()=>{const boot=await (await fetch('/api/suite/bootstrap')).json();const response=await fetch('/api/suite/native-tools/files/launch',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':boot.csrf},body:'{}'});return response.status;});assert.equal(forbidden,403);mark('Even an authenticated direct request cannot bypass the disabled native launch control');
  await page.goto(origin+'/#files');await page.locator('#file-workbench').waitFor();await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(artifacts,'suite-remote-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);mark('Remote Suite fits 375px with no browser exceptions');
  console.log(JSON.stringify({result:'passed',checks:checks.length,artifacts},null,2));
 }catch(error){if(page)try{await page.screenshot({path:path.join(artifacts,'suite-remote-failure.png'),fullPage:true});}catch{}throw error;}
 finally{if(browser)await browser.close();proxy.closeAllConnections();await new Promise(resolve=>proxy.close(resolve));try{if(localBoot)await fetch(local+'/api/suite/shutdown',{method:'POST',headers:{Origin:local,'Content-Type':'application/json','X-CSRF-Token':localBoot.csrf},body:'{}',signal:AbortSignal.timeout(5000)});}catch{}if(server.exitCode===null){await Promise.race([new Promise(resolve=>server.once('exit',resolve)),delay(5000)]);if(server.exitCode===null)server.kill();}fs.closeSync(log);}
}
main().catch(error=>{console.error(error.stack||error.message);process.exitCode=1;});
