# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pairing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pairing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpairing.proto\x12\x0b\x61\x64\x62.pairing\"q\n\rPairingPacket\x12(\n\x04init\x18\x01 \x01(\x0b\x32\x18.adb.pairing.PairingInitH\x00\x12,\n\x06result\x18\x02 \x01(\x0b\x32\x1a.adb.pairing.PairingResultH\x00\x42\x08\n\x06packet\"6\n\x0bPairingInit\x12\x14\n\x0cpairing_code\x18\x01 \x01(\x0c\x12\x11\n\tpeer_info\x18\x02 \x01(\x0c\" \n\rPairingResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pairing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAIRINGPACKET']._serialized_start=30
  _globals['_PAIRINGPACKET']._serialized_end=143
  _globals['_PAIRINGINIT']._serialized_start=145
  _globals['_PAIRINGINIT']._serialized_end=199
  _globals['_PAIRINGRESULT']._serialized_start=201
  _globals['_PAIRINGRESULT']._serialized_end=233
# @@protoc_insertion_point(module_scope)
